name: action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo add-apt-repository -y ppa:dreibh/ppa
          sudo apt update
          sudo apt install -y tox tshark frr p4lang-p4c
          sudo pip install tox-pip-version
          git clone git://github.com/mininet/mininet
          wget https://raw.githubusercontent.com/p4lang/behavioral-model/13d7267/mininet/p4_mininet.py
          pushd mininet
          git checkout -b mininet-2.3.0 2.3.0
          ./util/install.sh -nv
          popd
      - name: run test
        run: |
          sudo -E mn --switch ovs --test pingall
          sudo -E tox
