name: action
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          set -x

          # refs: https://github.com/p4lang/p4c#ubuntu
          source /etc/os-release
          echo "deb https://download.opensuse.org/repositories/home:/p4lang/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/home:p4lang.list
          curl -L "https://download.opensuse.org/repositories/home:/p4lang/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -

          sudo apt update
          sudo apt install -y tox tshark frr p4lang-p4c clang linux-headers-$(uname -r) bpfcc-tools bcc libnuma-dev python3.11 python2.7
          sudo ln -s /usr/include/asm-generic /usr/include/asm
          sudo pip install tox-pip-version

          # install mininet
          git clone https://github.com/mininet/mininet.git -b 2.3.0 --depth 1
          wget https://raw.githubusercontent.com/p4lang/behavioral-model/13d7267/mininet/p4_mininet.py
          pushd mininet
          ./util/install.sh -n
          popd

          # install libbpf
          grep CONFIG_BPF=y /boot/config-$(uname -r)
          grep CONFIG_BPF_SYSCALL=y /boot/config-$(uname -r)
          grep CONFIG_XDP_SOCKETS=y /boot/config-$(uname -r)
          git clone git://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git -b v5.15 --depth 1
          pushd ./bpf-next/tools/lib/bpf
          sudo make install
          sudo sh -c "echo /usr/local/lib64 >> /etc/ld.so.conf"
          sudo ldconfig
          popd

          # install ovs with afxdp
          git clone https://github.com/openvswitch/ovs.git -b v2.16.1 --depth 1
          pushd ovs
          ./boot.sh
          ./configure --enable-afxdp --with-debug
          make -j $(nproc)
          sudo make install
          popd
      - name: run test
        run: |
          sudo make -C ./ovs check-afxdp TESTSUITEFLAGS='1 3'
          sudo /usr/local/share/openvswitch/scripts/ovs-ctl start
          sudo -E mn --switch ovs --test pingall
          sudo -E tox
