name: action
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y tox tshark frr
          git clone git://github.com/mininet/mininet
          pushd mininet
          git checkout -b mininet-2.3.0 2.3.0
          ./util/install.sh -nv
          popd
      - name: run test
        run: |
          sudo -E mn --switch ovs --test pingall
          sudo -E tox
